### ISSUE TITLE
error: invalid use of incomplete type ‘X509 {aka struct x509_st}’

### ISSUE THREAD

**Issue by cclements** [snortadmin/snort3#28]
Receiving these errors:

```
Making all in appid
make[4]: Entering directory '/root/tools/snort3/src/network_inspectors/appid'
make[5]: Entering directory '/root/tools/snort3/src/network_inspectors/appid'
  CXX      service_plugins/service_ssl.o
service_plugins/service_ssl.cc: In function ‘bool parse_certificates(ServiceSSLData*)’:
service_plugins/service_ssl.cc:496:38: error: invalid use of incomplete type ‘X509 {aka struct x509_st}’
             char* start = strstr(cert->name, COMMON_NAME_STR);
                                      ^~
In file included from /usr/include/openssl/x509.h:20:0,
                 from service_plugins/service_ssl.cc:28:
/usr/include/openssl/ossl_typ.h:119:16: note: forward declaration of ‘X509 {aka struct x509_st}’
 typedef struct x509_st X509;
                ^~~~~~~
service_plugins/service_ssl.cc:513:32: error: invalid use of incomplete type ‘X509 {aka struct x509_st}’
             start = strstr(cert->name, ORG_NAME_STR);
                                ^~
In file included from /usr/include/openssl/x509.h:20:0,
                 from service_plugins/service_ssl.cc:28:
/usr/include/openssl/ossl_typ.h:119:16: note: forward declaration of ‘X509 {aka struct x509_st}’
 typedef struct x509_st X509;
                ^~~~~~~
make[5]: *** [Makefile:1017: service_plugins/service_ssl.o] Error 1
make[5]: Leaving directory '/root/tools/snort3/src/network_inspectors/appid'
make[4]: *** [Makefile:1053: all-recursive] Error 1
make[4]: Leaving directory '/root/tools/snort3/src/network_inspectors/appid'
make[3]: *** [Makefile:518: all-recursive] Error 1
make[3]: Leaving directory '/root/tools/snort3/src/network_inspectors'
make[2]: *** [Makefile:694: all-recursive] Error 1
make[2]: Leaving directory '/root/tools/snort3/src'
make[1]: *** [Makefile:520: all-recursive] Error 1
make[1]: Leaving directory '/root/tools/snort3'
make: *** [Makefile:429: all] Error 2
```

From the following build log:

https://gist.github.com/cclements/0a49bc5cc1258a93bc67f85e36e67d22

**Comment by cclements** [comment]
Manually specifying openssl-1.0 resolved this error:

./configure --with-openssl-includes=/usr/include/openssl-1.0/ --with-openssl-libraries=/usr/lib/openssl-1.0/

**Comment by snortadmin** [comment]
Thanks for posting the issue and resolution!

**Comment by loulansuiye** [comment]
it seems that does work at all

**Comment by v-sijeff** [comment]
I have been asked to modify a program which does not compile with openssl 1.1.  The error message is:

```
main.c: In function ‘do_signature’:
main.c:63:10: error: dereferencing pointer to incomplete type ‘X509 {aka struct x509_st}’
  memcpy(x->signature->data, sig_buf, sig_len);
          ^~
Makefile:54: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

I see where X509 is defined in a typedef in ossl_typ.h.   Not being all that familiar with this software, I'd love a hint or a pointer to a hint which has the solution, please.

Thank you.

**Comment by chirayu-xx** [comment]
Im also stucked at this point even the openssl documentation is not helping me to find the structure which can help to know correct way to access.

**Comment by chirayu-xx** [comment]
How to manually add the path in CMakeList.txt for  specifying the version of OpenSSL
